#!/bin/bash
# install test app in dev container

cd /workspace

# upgrade pip
python -m pip install --upgrade pip

# install with all extras in editable mode
pip install --upgrade -r requirements.txt

# install pre-commit hooks to git
pre-commit install
