name: Static Code Analysis

on: push

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    name: Static Code Analysis
    steps:
      - uses: actions/checkout@v3

      - uses: pre-commit/action@v3.0.0
        env:
          SKIP: no-commit-to-branch
      - name: black
        run: |
          black --check .
      - name: isort
        run: |
          isort --check --profile black .
      - name: mypy
        run: |
          mypy .
      - name: pylint
        run: |
          pylint ./steps
      - name: flake8
        run: |
          flake8 --config .flake8
      - name: bandit
        run: |
          bandit -r .
      - name: Check license header and file
        run: |
          ./scripts/license_checker.py
