name: Static Code Analysis

on: push

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    name: Static Code Analysis
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt -r requirements-dev.txt

      - uses: pre-commit/action@v3.0.0
        env:
          SKIP: no-commit-to-branch
      - name: ruff
        uses: chartboost/ruff-action@v1
      - name: black
        run: |
          black --check .
      - name: Check license header and file
        run: |
          ./scripts/license_checker.py
